controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_catalogue:
    path: /catalogue
    controller: App\Controller\CatalogueController::index
    methods: [GET]


